### PR TITLE
Baseline fixes

### PR DESCRIPTION
**Pull request by santipuch590**

### CODE REVIEW

**Comment by lluisgomez** [comment]
We have changed the optimizer factory in the base repo as suggested.
I'm not sure if tf.pack being deprecated in 1.0.0 is an issue for us right now. I guess we target r0.12 for the master, but I'll double check it.
Thanks!

**Comment by dvazquezcvc** [comment]
Thanks a lot for the pull request!!

**Comment by santipuch590** [comment]
No problem, I hope it will be useful!

**Comment by lluisgomez** [comment]
I was only hesitant because I was not sure all our TF code works well with 1.0.0, especially the yolo model.
Now I've checked and it only requires minimal changes, so everything is ok :)
Thanks!

**Pull request merged**
